{
  "formatVersion": "1.1",
  "component": {
    "group": "net.fabricmc",
    "module": "fabric-loom",
    "version": "1.17-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "fabric-loom-1.17-SNAPSHOT.jar",
          "url": "fabric-loom-1.17-SNAPSHOT.jar",
          "size": 1433288,
          "sha512": "ea83ed06bc8059a6bb23deb46224c30ac643f59219ba03cb1488c7a533be6fc937caff8a8e6e13903179dd3f736d325f6fdb168a52ebeca9e44fed9a5f3bcdb9",
          "sha256": "fab71d6bb60d98be9f39a31222fa060b67f6e148ee1699bbfa376d6b5bc84138",
          "sha1": "17a9a1afcea89eccc19f2e2e57a43b5923047675",
          "md5": "a277e572e530ea77f1fcf41e9fc0ab99"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "9.5.0",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "stitch",
          "version": {
            "requires": "0.6.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "enigma"
            },
            {
              "group": "*",
              "module": "guava"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "tiny-remapper",
          "version": {
            "requires": "0.14.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "class-tweaker",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "mapping-io",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "lorenz-tiny",
          "version": {
            "requires": "4.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loom-native",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "mercury",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "mercurymixin",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "net.fabricmc.unpick",
          "module": "unpick",
          "version": {
            "requires": "3.0.0-beta.13"
          }
        },
        {
          "group": "net.fabricmc.unpick",
          "module": "unpick-format-utils",
          "version": {
            "requires": "3.0.0-beta.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-metadata-jvm",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fabric-loom-1.17-SNAPSHOT.jar",
          "url": "fabric-loom-1.17-SNAPSHOT.jar",
          "size": 1433288,
          "sha512": "ea83ed06bc8059a6bb23deb46224c30ac643f59219ba03cb1488c7a533be6fc937caff8a8e6e13903179dd3f736d325f6fdb168a52ebeca9e44fed9a5f3bcdb9",
          "sha256": "fab71d6bb60d98be9f39a31222fa060b67f6e148ee1699bbfa376d6b5bc84138",
          "sha1": "17a9a1afcea89eccc19f2e2e57a43b5923047675",
          "md5": "a277e572e530ea77f1fcf41e9fc0ab99"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fabric-loom-1.17-SNAPSHOT-sources.jar",
          "url": "fabric-loom-1.17-SNAPSHOT-sources.jar",
          "size": 860004,
          "sha512": "c93c14820481acdf7ce450ac231dcb5b5f7522c17f6b9351f50a6e5f690bdc3c8eb3c3262a4ec30a4cecd6b7f1c0eb522423ce1a6db135eb957b13285578986e",
          "sha256": "6dd9d3ced849bd088ce0778aa0c17cfda7edc5d7ea357ec324a02cf3cbbc9f58",
          "sha1": "18383257138086815f8f8677359b9c4df7100da9",
          "md5": "2e0c2b3d78c223b500eaa3c9f7079a05"
        }
      ]
    }
  ]
}
