{
  "formatVersion": "1.1",
  "component": {
    "group": "net.fabricmc",
    "module": "fabric-loom",
    "version": "1.17-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "fabric-loom-1.17-SNAPSHOT.jar",
          "url": "fabric-loom-1.17-SNAPSHOT.jar",
          "size": 1433255,
          "sha512": "c4906a35cdfed07dab761120665b775c8e30a7d25b64b05ccc591a5750edb333dad950cd0ca513dd7ba799dce99a0c5501cc99ebfffb1cf5e747a752ae07995d",
          "sha256": "f6eed23a352b8b7d59eacf5ebede5ee6cc744db4c0a00f964ad5d4fff9c8e8af",
          "sha1": "1d2b030f3c88a5bf72479931137aac05f85aad22",
          "md5": "767694a2d2a54be600d4e1d94930c286"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "9.5.0",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "stitch",
          "version": {
            "requires": "0.6.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "enigma"
            },
            {
              "group": "*",
              "module": "guava"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "tiny-remapper",
          "version": {
            "requires": "0.14.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "class-tweaker",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "mapping-io",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "lorenz-tiny",
          "version": {
            "requires": "4.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loom-native",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "mercury",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "mercurymixin",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "net.fabricmc.unpick",
          "module": "unpick",
          "version": {
            "requires": "3.0.0-beta.13"
          }
        },
        {
          "group": "net.fabricmc.unpick",
          "module": "unpick-format-utils",
          "version": {
            "requires": "3.0.0-beta.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-metadata-jvm",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fabric-loom-1.17-SNAPSHOT.jar",
          "url": "fabric-loom-1.17-SNAPSHOT.jar",
          "size": 1433255,
          "sha512": "c4906a35cdfed07dab761120665b775c8e30a7d25b64b05ccc591a5750edb333dad950cd0ca513dd7ba799dce99a0c5501cc99ebfffb1cf5e747a752ae07995d",
          "sha256": "f6eed23a352b8b7d59eacf5ebede5ee6cc744db4c0a00f964ad5d4fff9c8e8af",
          "sha1": "1d2b030f3c88a5bf72479931137aac05f85aad22",
          "md5": "767694a2d2a54be600d4e1d94930c286"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fabric-loom-1.17-SNAPSHOT-sources.jar",
          "url": "fabric-loom-1.17-SNAPSHOT-sources.jar",
          "size": 860381,
          "sha512": "0dccd1d6367ae28faf4e0f0737c3b52b83d71e1b2063dcb00e0cc9e00902df711ae1eec7640ae9e605bb3f9bd669bbdda089fa3e8d77ee0a9ea0d9cf5e4aaf5f",
          "sha256": "105eb2a36411c5fcf06dc22e5a4a8cb7aa15b27a2f453102c0e58d10c34e0dd2",
          "sha1": "4c87766e6a9262937d20b492c3dd34925137bbb1",
          "md5": "d3756ddebc7bbc33bdead47d3513dc8d"
        }
      ]
    }
  ]
}
