{
  "formatVersion": "1.1",
  "component": {
    "group": "net.fabricmc",
    "module": "fabric-loom",
    "version": "1.17-ii-validation-1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "fabric-loom-1.17-ii-validation-1.jar",
          "url": "fabric-loom-1.17-ii-validation-1.jar",
          "size": 1433357,
          "sha512": "c25513b116f35e4e3c11aca695d0bc2b3619b3c77d7b30aefe0d8086ad3273bad88a1f9586f7ccb82cb47fafc3e8e6e7f2edce75eba770a9478df38d881a6259",
          "sha256": "18a68530e928eee5d51d83176faf91a2eaaf708c64042775b7ea5b7dca967926",
          "sha1": "73159a42c0b1cc163ee49c0ca84466df9dde2a43",
          "md5": "fb74ef4c40acaf9af2587750131f8ae6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "9.5.0",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "stitch",
          "version": {
            "requires": "0.6.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "enigma"
            },
            {
              "group": "*",
              "module": "guava"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "tiny-remapper",
          "version": {
            "requires": "0.14.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "class-tweaker",
          "version": {
            "requires": "0.3.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "mapping-io",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "lorenz-tiny",
          "version": {
            "requires": "4.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loom-native",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "mercury",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "mercurymixin",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "net.fabricmc.unpick",
          "module": "unpick",
          "version": {
            "requires": "3.0.0-beta.13"
          }
        },
        {
          "group": "net.fabricmc.unpick",
          "module": "unpick-format-utils",
          "version": {
            "requires": "3.0.0-beta.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-metadata-jvm",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fabric-loom-1.17-ii-validation-1.jar",
          "url": "fabric-loom-1.17-ii-validation-1.jar",
          "size": 1433357,
          "sha512": "c25513b116f35e4e3c11aca695d0bc2b3619b3c77d7b30aefe0d8086ad3273bad88a1f9586f7ccb82cb47fafc3e8e6e7f2edce75eba770a9478df38d881a6259",
          "sha256": "18a68530e928eee5d51d83176faf91a2eaaf708c64042775b7ea5b7dca967926",
          "sha1": "73159a42c0b1cc163ee49c0ca84466df9dde2a43",
          "md5": "fb74ef4c40acaf9af2587750131f8ae6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fabric-loom-1.17-ii-validation-1-sources.jar",
          "url": "fabric-loom-1.17-ii-validation-1-sources.jar",
          "size": 860294,
          "sha512": "0da2715a988a8e247778b8987fc79c5fad61c828bf200790bcd895c5c76adda951249e7f2320bfe0103d23428b1eab7915f8d45b2858753aa9b6fe159fe75408",
          "sha256": "b4dc618c773f10276a51e5996c01484e456bed98e63154c723a305e2d0714178",
          "sha1": "9d2ffb82a6407739dd39ac8bc4f3669a11ad712b",
          "md5": "8ce278acdef6d83d133bb1fd631f686b"
        }
      ]
    }
  ]
}
